/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Tui */

#ifndef _Included_Tui
#define _Included_Tui
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Tui
 * Method:    clrscr
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Tui_clrscr
  (JNIEnv *, jobject);

/*
 * Class:     Tui
 * Method:    gotoxy
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_Tui_gotoxy
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     Tui
 * Method:    setTextAttribute
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_Tui_setTextAttribute
  (JNIEnv *, jobject, jint);

/*
 * Class:     Tui
 * Method:    getch
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Tui_getch
  (JNIEnv *, jobject);

/*
 * Class:     Tui
 * Method:    kbhit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Tui_kbhit
  (JNIEnv *, jobject);

/*
 * Class:     Tui
 * Method:    hideCursor
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Tui_hideCursor
  (JNIEnv *, jobject);

/*
 * Class:     Tui
 * Method:    showCursor
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Tui_showCursor
  (JNIEnv *, jobject);

/*
 * Class:     Tui
 * Method:    setCursorSize
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_Tui_setCursorSize
  (JNIEnv *, jobject, jint);

/*
 * Class:     Tui
 * Method:    getWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Tui_getWidth
  (JNIEnv *, jobject);

/*
 * Class:     Tui
 * Method:    getHeight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Tui_getHeight
  (JNIEnv *, jobject);

/*
 * Class:     Tui
 * Method:    setWindow
 * Signature: (IIIIZ)V
 */
JNIEXPORT void JNICALL Java_Tui_setWindow
  (JNIEnv *, jobject, jint, jint, jint, jint, jboolean);

#ifdef __cplusplus
}
#endif
#endif
